version: '3'

services:
  to_do_app:
    image: module5_todo:dev
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ./todo_app
        target: /app/todo_app